### ISSUE TITLE
node_modules in the repo?

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/wp-lambda-deploy#1]
Not an issue, but I'm curious why you've decided to check in the node_modules directory. I thought common practice was to check in the package.json file, but gitignore the node_modules directory (cf. ruby's Gemfile and gems)

**Comment by ollietreend** [comment]
Hi @digitalronin (apologies, I've only just seen this)

We've committed the `node_modules` directory to ensure modules are compiled with node 6 so that it'll run on lambda. My dev machine is running an older version of node for compatibility with an older project. At the time this seemed like less hassle than setting up [nvm](https://github.com/creationix/nvm), although perhaps it'd be worth revisiting this at some point.

**Comment by digitalronin** [comment]
That makes perfect sense. Thanks.
